%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\NaStA XRF_Measurements Samples from SPb and old Quarries_2021\Sample_1_FountainNearKazan_St_Petersburg_chemistry-804043-2021-11-03.xls
%    Worksheet: Sample_1_FountainNearKazan_St_P
%
% Auto-generated by MATLAB on 11-Feb-2022 16:47:57

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 91);

% Specify sheet and range
opts.Sheet = "Sample_1_FountainNearKazan_St_P";
opts.DataRange = "A2:CM83";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "MgError1s", "AlConcentration", "AlError1s", "SiConcentration", "SiError1s", "PConcentration", "PError1s", "SConcentration", "SError1s", "KConcentration", "KError1s", "CaConcentration", "CaError1s", "TiConcentration", "TiError1s", "VConcentration", "VError1s", "CrConcentration", "CrError1s", "MnConcentration", "MnError1s", "FeConcentration", "FeError1s", "CoConcentration", "CoError1s", "NiConcentration", "NiError1s", "CuConcentration", "CuError1s", "ZnConcentration", "ZnError1s", "AsConcentration", "AsError1s", "SeConcentration", "SeError1s", "RbConcentration", "RbError1s", "SrConcentration", "SrError1s", "YConcentration", "YError1s", "ZrConcentration", "ZrError1s", "NbConcentration", "NbError1s", "MoConcentration", "MoError1s", "AgConcentration", "AgError1s", "CdConcentration", "CdError1s", "SnConcentration", "SnError1s", "SbConcentration", "SbError1s", "BaConcentration", "BaError1s", "LaConcentration", "LaError1s", "CeConcentration", "CeError1s", "PrConcentration", "PrError1s", "NdConcentration", "NdError1s", "TaConcentration", "TaError1s", "WConcentration", "WError1s", "AuConcentration", "AuError1s", "HgConcentration", "HgError1s", "PbConcentration", "PbError1s", "BiConcentration", "BiError1s", "ThConcentration", "ThError1s", "UConcentration", "UError1s", "LEConcentration", "LEError1s"];
opts.SelectedVariableNames = ["SampleID", "MgConcentration", "MgError1s", "AlConcentration", "AlError1s", "SiConcentration", "SiError1s", "PConcentration", "PError1s", "SConcentration", "SError1s", "KConcentration", "KError1s", "CaConcentration", "CaError1s", "TiConcentration", "TiError1s", "VConcentration", "VError1s", "CrConcentration", "CrError1s", "MnConcentration", "MnError1s", "FeConcentration", "FeError1s", "CoConcentration", "CoError1s", "NiConcentration", "NiError1s", "CuConcentration", "CuError1s", "ZnConcentration", "ZnError1s", "AsConcentration", "AsError1s", "SeConcentration", "SeError1s", "RbConcentration", "RbError1s", "SrConcentration", "SrError1s", "YConcentration", "YError1s", "ZrConcentration", "ZrError1s", "NbConcentration", "NbError1s", "MoConcentration", "MoError1s", "AgConcentration", "AgError1s", "CdConcentration", "CdError1s", "SnConcentration", "SnError1s", "SbConcentration", "SbError1s", "BaConcentration", "BaError1s", "LaConcentration", "LaError1s", "CeConcentration", "CeError1s", "PrConcentration", "PrError1s", "NdConcentration", "NdError1s", "TaConcentration", "TaError1s", "WConcentration", "WError1s", "AuConcentration", "AuError1s", "HgConcentration", "HgError1s", "PbConcentration", "PbError1s", "BiConcentration", "BiError1s", "ThConcentration", "ThError1s", "UConcentration", "UError1s", "LEConcentration", "LEError1s"];
opts.VariableTypes = ["char", "char", "char", "char", "string", "char", "char", "categorical", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double"];

% Replace cats with double
cat_idx = contains(opts.VariableTypes,'categorical');
opts.VariableTypes(cat_idx) = {'double'};

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "PConcentration", "SConcentration", "CoConcentration", "NiConcentration", "AsConcentration", "SeConcentration", "MoConcentration", "AgConcentration", "CdConcentration", "SnConcentration", "SbConcentration", "LaConcentration", "PrConcentration", "NdConcentration", "WConcentration", "AuConcentration", "HgConcentration", "BiConcentration", "ThConcentration", "UConcentration"], "EmptyFieldRule", "auto");

% Import the data
Sample1 = readtable("C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\XRF\Sample_1_FountainNearKazan_St_Petersburg_chemistry-804043-2021-11-03.xls", opts, "UseExcel", false);

%% Get indeces
% Error idx from variables
Errors_idx = contains(opts.SelectedVariableNames,'Error');
Errors_idx(1) = '';
% REE index
REE = contains(Sample1.SampleID,'REE'); 
%% REE Data
% REE elements: Ba, La, Ce, Pr, Nd, Ta, 
% Data with REE
Sample1_REE = Sample1(REE,:);
% Get object/sample names
Sample1_REE_obj = Sample1_REE.SampleID;
% Fetch only the numbers of the samples
[~,remain] = strtok(Sample1_REE_obj,'ruutu');
[~,remain] = strtok(remain,{'1','2','3','4'});
[token,remain] = strtok(remain,'-');
[~,remain] = strtok(remain,{'1','2','3','4','5','6','7','8','9'});
% Write objects as s1_ree_<square>_<number>
s1_ree_obj = 's1_ree_'+token+'_'+remain;

% Table to matrix
s1_ree_data = Sample1_REE(:,2:end).Variables;
% Remove errors
s1_ree_data(:,Errors_idx) = '';

s1_ree_var = Sample1_REE.Properties.VariableNames(2:end);
% Remove errors
s1_ree_var(Errors_idx) = '';
% Erase "Concentration" from variable names
s1_ree_var = erase(s1_ree_var,"Concentration");
%% Data without REE
% Data without REE
Sample1_ = Sample1(~REE,:);
% Get object/sample names
Sample1_obj = Sample1_.SampleID;
% Fetch only the numbers of the samples
[~,remain] = strtok(Sample1_REE_obj,'ruutu');
[~,remain] = strtok(remain,{'1','2','3','4'});
[token,remain] = strtok(remain,'-');
[~,remain] = strtok(remain,{'1','2','3','4','5','6','7','8','9'});
% Write objects as s1_<square>_<number>
s1_obj = 's1_'+token+'_'+remain;

% Table to matrix
s1_data = Sample1_(:,2:end).Variables;
% Remove errors
s1_data(:,Errors_idx) = '';

s1_var = Sample1_.Properties.VariableNames(2:end);
% Remove errors
s1_var(Errors_idx) = '';
% Erase "Concentration" from variable names
s1_var = erase(s1_var,"Concentration");
%% Clear temporary variables
clear opts