%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\XRF\NaStA_Paavo_Härmä_Heponiemi_2_ja3_GeochemREE_Chemistry-ExportData-2020-07-09.xls
%    Worksheet: NaStA_Paavo_Härmä_Heponiemi_2_j
%
% Auto-generated by MATLAB on 17-Feb-2022 09:04:31

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 91);

% Specify sheet and range
opts.Sheet = "NaStA_Paavo_Härmä_Heponiemi_2_j";
opts.DataRange = "A2:CM52";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "MgError1s", "AlConcentration", "AlError1s", "SiConcentration", "SiError1s", "PConcentration", "PError1s", "SConcentration", "SError1s", "KConcentration", "KError1s", "CaConcentration", "CaError1s", "TiConcentration", "TiError1s", "VConcentration", "VError1s", "CrConcentration", "CrError1s", "MnConcentration", "MnError1s", "FeConcentration", "FeError1s", "CoConcentration", "CoError1s", "NiConcentration", "NiError1s", "CuConcentration", "CuError1s", "ZnConcentration", "ZnError1s", "AsConcentration", "AsError1s", "SeConcentration", "SeError1s", "RbConcentration", "RbError1s", "SrConcentration", "SrError1s", "YConcentration", "YError1s", "ZrConcentration", "ZrError1s", "NbConcentration", "NbError1s", "MoConcentration", "MoError1s", "AgConcentration", "AgError1s", "CdConcentration", "CdError1s", "SnConcentration", "SnError1s", "SbConcentration", "SbError1s", "BaConcentration", "BaError1s", "LaConcentration", "LaError1s", "CeConcentration", "CeError1s", "PrConcentration", "PrError1s", "NdConcentration", "NdError1s", "TaConcentration", "TaError1s", "WConcentration", "WError1s", "AuConcentration", "AuError1s", "HgConcentration", "HgError1s", "PbConcentration", "PbError1s", "BiConcentration", "BiError1s", "ThConcentration", "ThError1s", "UConcentration", "UError1s", "LEConcentration", "LEError1s"];
opts.SelectedVariableNames = ["SampleID", "MgConcentration", "MgError1s", "AlConcentration", "AlError1s", "SiConcentration", "SiError1s", "PConcentration", "PError1s", "SConcentration", "SError1s", "KConcentration", "KError1s", "CaConcentration", "CaError1s", "TiConcentration", "TiError1s", "VConcentration", "VError1s", "CrConcentration", "CrError1s", "MnConcentration", "MnError1s", "FeConcentration", "FeError1s", "CoConcentration", "CoError1s", "NiConcentration", "NiError1s", "CuConcentration", "CuError1s", "ZnConcentration", "ZnError1s", "AsConcentration", "AsError1s", "SeConcentration", "SeError1s", "RbConcentration", "RbError1s", "SrConcentration", "SrError1s", "YConcentration", "YError1s", "ZrConcentration", "ZrError1s", "NbConcentration", "NbError1s", "MoConcentration", "MoError1s", "AgConcentration", "AgError1s", "CdConcentration", "CdError1s", "SnConcentration", "SnError1s", "SbConcentration", "SbError1s", "BaConcentration", "BaError1s", "LaConcentration", "LaError1s", "CeConcentration", "CeError1s", "PrConcentration", "PrError1s", "NdConcentration", "NdError1s", "TaConcentration", "TaError1s", "WConcentration", "WError1s", "AuConcentration", "AuError1s", "HgConcentration", "HgError1s", "PbConcentration", "PbError1s", "BiConcentration", "BiError1s", "ThConcentration", "ThError1s", "UConcentration", "UError1s", "LEConcentration", "LEError1s"];
opts.VariableTypes = ["char", "char", "char", "char", "string", "char", "char", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "string", "string", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double"];

% Replace cats with double
cat_idx = contains(opts.VariableTypes,'categorical');
opts.VariableTypes(cat_idx) = {'double'};

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "AuConcentration", "AuError1s"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "TiConcentration", "VConcentration", "CrConcentration", "MnConcentration", "CoConcentration", "NiConcentration", "CuConcentration", "ZnConcentration", "AsConcentration", "SeConcentration", "AgConcentration", "CdConcentration", "SnConcentration", "SbConcentration", "PrConcentration", "NdConcentration", "TaConcentration", "WConcentration", "AuConcentration", "AuError1s", "HgConcentration", "BiConcentration", "ThConcentration", "UConcentration"], "EmptyFieldRule", "auto");

% Import the data
Heponiemi_raw = readtable("C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\XRF\NaStA_Paavo_Härmä_Heponiemi_2_ja3_GeochemREE_Chemistry-ExportData-2020-07-09.xls", opts, "UseExcel", false);

% Error idx from variables
Errors_idx = contains(opts.SelectedVariableNames,'Error');
% Errors_idx([72,73]) = true;
Errors_idx(1) = '';
%%
% Get object/sample names
Heponiemi_REE_obj = Heponiemi_raw.SampleID;
% Fetch only the numbers of the samples
[token,remain] = strtok(Heponiemi_REE_obj,{'1','2','3'});
[token1,remain1] = strtok(remain,{'-','_'});
[token2,remain2] = strtok(remain,{'1','2','3','4','R'});
% Write objects as h_ree_<square>_<number>
h_ree_obj = 'h_ree_'+token1+'_'+remain2;

% Table to matrix
h_ree_data = Heponiemi_raw(:,2:end).Variables;
h_ree_data = double(h_ree_data);
% Remove errors
h_ree_data(:,Errors_idx) = '';

h_ree_var = Heponiemi_raw.Properties.VariableNames(2:end);
% Remove errors
h_ree_var(Errors_idx) = '';
% Erase "Concentration" from variable names
h_ree_var = erase(h_ree_var,"Concentration");
%% Clear temporary variables
clear opts