%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\NaStA XRF_Measurements Samples from SPb and old Quarries_2021\NaStA Hailniemi XRF_Mittaukset 2021_11_11_chemistry-ExportData.csv
%
% Auto-generated by MATLAB on 10-Feb-2022 16:07:06

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 97);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "Var9", "AlConcentration", "Var11", "SiConcentration", "Var13", "PConcentration", "Var15", "SConcentration", "Var17", "KConcentration", "Var19", "CaConcentration", "Var21", "TiConcentration", "Var23", "VConcentration", "Var25", "CrConcentration", "Var27", "MnConcentration", "Var29", "FeConcentration", "Var31", "CoConcentration", "Var33", "NiConcentration", "Var35", "CuConcentration", "Var37", "ZnConcentration", "Var39", "AsConcentration", "Var41", "SeConcentration", "Var43", "RbConcentration", "Var45", "SrConcentration", "Var47", "YConcentration", "Var49", "ZrConcentration", "Var51", "NbConcentration", "Var53", "MoConcentration", "Var55", "AgConcentration", "Var57", "CdConcentration", "Var59", "SnConcentration", "Var61", "SbConcentration", "Var63", "BaConcentration", "Var65", "LaConcentration", "Var67", "CeConcentration", "Var69", "PrConcentration", "Var71", "NdConcentration", "Var73", "TaConcentration", "Var75", "WConcentration", "Var77", "AuConcentration", "Var79", "HgConcentration", "Var81", "PbConcentration", "Var83", "BiConcentration", "Var85", "ThConcentration", "Var87", "UConcentration", "Var89", "LEConcentration", "Var91", "Var92", "Var93", "Var94", "Var95", "Var96", "Var97"];
opts.SelectedVariableNames = ["SampleID", "MgConcentration", "AlConcentration", "SiConcentration", "PConcentration", "SConcentration", "KConcentration", "CaConcentration", "TiConcentration", "VConcentration", "CrConcentration", "MnConcentration", "FeConcentration", "CoConcentration", "NiConcentration", "CuConcentration", "ZnConcentration", "AsConcentration", "SeConcentration", "RbConcentration", "SrConcentration", "YConcentration", "ZrConcentration", "NbConcentration", "MoConcentration", "AgConcentration", "CdConcentration", "SnConcentration", "SbConcentration", "BaConcentration", "LaConcentration", "CeConcentration", "PrConcentration", "NdConcentration", "TaConcentration", "WConcentration", "AuConcentration", "HgConcentration", "PbConcentration", "BiConcentration", "ThConcentration", "UConcentration", "LEConcentration"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "categorical", "string", "double", "string", "double", "string", "double", "string", "double", "string", "double", "string", "double", "string", "double", "string", "categorical", "string", "categorical", "string", "double", "string", "double", "string", "categorical", "string", "categorical", "string", "categorical", "string", "double", "string", "categorical", "string", "categorical", "string", "double", "string", "double", "string", "double", "string", "double", "string", "double", "string", "double", "string", "categorical", "string", "categorical", "string", "categorical", "string", "categorical", "string", "double", "string", "double", "string", "double", "string", "categorical", "string", "categorical", "string", "categorical", "string", "categorical", "string", "categorical", "string", "categorical", "string", "double", "string", "categorical", "string", "double", "string", "double", "string", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "Var9", "Var11", "Var13", "Var15", "Var17", "Var19", "Var21", "Var23", "Var25", "Var27", "Var29", "Var31", "Var33", "Var35", "Var37", "Var39", "Var41", "Var43", "Var45", "Var47", "Var49", "Var51", "Var53", "Var55", "Var57", "Var59", "Var61", "Var63", "Var65", "Var67", "Var69", "Var71", "Var73", "Var75", "Var77", "Var79", "Var81", "Var83", "Var85", "Var87", "Var89", "Var91", "Var92", "Var93", "Var94", "Var95", "Var96", "Var97"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "Var9", "Var11", "Var13", "Var15", "Var17", "Var19", "Var21", "Var23", "VConcentration", "Var25", "CrConcentration", "Var27", "Var29", "Var31", "CoConcentration", "Var33", "NiConcentration", "Var35", "CuConcentration", "Var37", "Var39", "AsConcentration", "Var41", "SeConcentration", "Var43", "Var45", "Var47", "Var49", "Var51", "Var53", "Var55", "AgConcentration", "Var57", "CdConcentration", "Var59", "SnConcentration", "Var61", "SbConcentration", "Var63", "Var65", "Var67", "Var69", "PrConcentration", "Var71", "NdConcentration", "Var73", "TaConcentration", "Var75", "WConcentration", "Var77", "AuConcentration", "Var79", "HgConcentration", "Var81", "Var83", "BiConcentration", "Var85", "Var87", "Var89", "Var91", "Var92", "Var93", "Var94", "Var95", "Var96", "Var97"], "EmptyFieldRule", "auto");

% Import the data
Hailniemi = readtable("C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\NaStA XRF_Measurements Samples from SPb and old Quarries_2021\NaStA Hailniemi XRF_Mittaukset 2021_11_11_chemistry-ExportData.csv", opts);

REE = contains(Hailniemi.SampleID,'REE'); % REE index

Hailniemi_REE = Hailniemi(REE,:);
Hailniemi_obj = Hailniemi_REE.SampleID;
% Kirjoita obj lyhyempään muotoon esim Hail_1_1

Hailniemi_data = Hailniemi_REE(:,2:end);

% Muuta data matriisi muotoon
Hailniemi_data = table2array(Hailniemi_data);

varREE = Hailniemi_REE.Properties.VariableNames(2:end);
% Kirjoita var lyhyempään muotoon esim Mg, Al, Si

% Tee sama myös Geochem datalle
%% Clear temporary variables
clear opts