%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\NaStA XRF_Measurements Samples from SPb and old Quarries_2021\NaStA Hailniemi XRF_Mittaukset 2021_11_11_chemistry-ExportData.xls
%    Worksheet: NaStA_XRF_Mittaukset_Hailniemi_
%
% Auto-generated by MATLAB on 11-Feb-2022 10:39:40

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 91);

% Specify sheet and range
opts.Sheet = "NaStA_XRF_Mittaukset_Hailniemi_";
opts.DataRange = "A1:CM91";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "MgError1s", "AlConcentration", "AlError1s", "SiConcentration", "SiError1s", "PConcentration", "PError1s", "SConcentration", "SError1s", "KConcentration", "KError1s", "CaConcentration", "CaError1s", "TiConcentration", "TiError1s", "VConcentration", "VError1s", "CrConcentration", "CrError1s", "MnConcentration", "MnError1s", "FeConcentration", "FeError1s", "CoConcentration", "CoError1s", "NiConcentration", "NiError1s", "CuConcentration", "CuError1s", "ZnConcentration", "ZnError1s", "AsConcentration", "AsError1s", "SeConcentration", "SeError1s", "RbConcentration", "RbError1s", "SrConcentration", "SrError1s", "YConcentration", "YError1s", "ZrConcentration", "ZrError1s", "NbConcentration", "NbError1s", "MoConcentration", "MoError1s", "AgConcentration", "AgError1s", "CdConcentration", "CdError1s", "SnConcentration", "SnError1s", "SbConcentration", "SbError1s", "BaConcentration", "BaError1s", "LaConcentration", "LaError1s", "CeConcentration", "CeError1s", "PrConcentration", "PrError1s", "NdConcentration", "NdError1s", "TaConcentration", "TaError1s", "WConcentration", "WError1s", "AuConcentration", "AuError1s", "HgConcentration", "HgError1s", "PbConcentration", "PbError1s", "BiConcentration", "BiError1s", "ThConcentration", "ThError1s", "UConcentration", "UError1s", "LEConcentration", "LEError1s"];

opts.SelectedVariableNames = ["SampleID", "MgConcentration", "MgError1s", "AlConcentration", "AlError1s", "SiConcentration", "SiError1s", "PConcentration", "PError1s", "SConcentration", "SError1s", "KConcentration", "KError1s", "CaConcentration", "CaError1s", "TiConcentration", "TiError1s", "VConcentration", "VError1s", "CrConcentration", "CrError1s", "MnConcentration", "MnError1s", "FeConcentration", "FeError1s", "CoConcentration", "CoError1s", "NiConcentration", "NiError1s", "CuConcentration", "CuError1s", "ZnConcentration", "ZnError1s", "AsConcentration", "AsError1s", "SeConcentration", "SeError1s", "RbConcentration", "RbError1s", "SrConcentration", "SrError1s", "YConcentration", "YError1s", "ZrConcentration", "ZrError1s", "NbConcentration", "NbError1s", "MoConcentration", "MoError1s", "AgConcentration", "AgError1s", "CdConcentration", "CdError1s", "SnConcentration", "SnError1s", "SbConcentration", "SbError1s", "BaConcentration", "BaError1s", "LaConcentration", "LaError1s", "CeConcentration", "CeError1s", "PrConcentration", "PrError1s", "NdConcentration", "NdError1s", "TaConcentration", "TaError1s", "WConcentration", "WError1s", "AuConcentration", "AuError1s", "HgConcentration", "HgError1s", "PbConcentration", "PbError1s", "BiConcentration", "BiError1s", "ThConcentration", "ThError1s", "UConcentration", "UError1s", "LEConcentration", "LEError1s"];
opts.VariableTypes = ["char", "char", "char", "char", "string", "char", "char", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Replace cats with double
cat_idx = contains(opts.VariableTypes,'categorical');
opts.VariableTypes(cat_idx) = {'double'};

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "SampleID", "Var6", "Var7", "MgConcentration", "VConcentration", "CrConcentration", "CoConcentration", "NiConcentration", "CuConcentration", "AsConcentration", "SeConcentration", "AgConcentration", "CdConcentration", "SnConcentration", "SbConcentration", "PrConcentration", "NdConcentration", "TaConcentration", "WConcentration", "AuConcentration", "HgConcentration", "BiConcentration"], "EmptyFieldRule", "auto");

% Import the data
Hailniemi = readtable("C:\Users\Allu\Desktop\Töissä\Masters Thesis\Data\XRF\NaStA Hailniemi XRF_Mittaukset 2021_11_11_chemistry-ExportData.xls", opts, "UseExcel", false);
%% Get indeces
% Error idx from variables
Errors_idx = contains(opts.SelectedVariableNames,'Error');
Errors_idx(1) = '';
% REE index
REE = contains(Hailniemi.SampleID,'REE'); 
%% REE Data
% REE elements: Ba, La, Ce, Pr, Nd, Ta, 
% Data with REE
Hailniemi_REE = Hailniemi(REE,:);
% Get object/sample names
Hailniemi_REE_obj = Hailniemi_REE.SampleID;
% Fetch only the numbers of the samples
[~,remain] = strtok(Hailniemi_REE_obj,{'1','2','3','4'});
% Write objects as hn_ree_<square>_<number>
hn_ree_obj = 'hn_ree_'+remain;

% Table to matrix
hn_ree_data = Hailniemi_REE(:,2:end).Variables;
% Remove errors
hn_ree_data(:,Errors_idx) = '';

hn_ree_var = Hailniemi_REE.Properties.VariableNames(2:end);
% Remove errors
hn_ree_var(Errors_idx) = '';
% Erase "Concentration" from variable names
hn_ree_var = erase(hn_ree_var,"Concentration");
%% Data without REE
% Data without REE
Hailniemi_ = Hailniemi(~REE,:);
Hailniemi_(1,:) = [];
% Get object/sample names
Hailniemi_obj = Hailniemi_.SampleID;
% Fetch only the numbers of the samples
[~,remain] = strtok(Hailniemi_obj,{'1','2','3','4'});
% Write objects as hn_ree_<square>_<number>
hn_obj = 'hn_'+remain;

% Table to matrix
hn_data = Hailniemi_(:,2:end).Variables;
% Remove errors
hn_data(:,Errors_idx) = '';

hn_var = Hailniemi_.Properties.VariableNames(2:end);
% Remove errors
hn_var(Errors_idx) = '';
% Erase "Concentration" from variable names
hn_var = erase(hn_var,"Concentration");

%% Clear temporary variables
clear opts